"""baseline

Revision ID: 35fbd8e86e99
Revises: 
Create Date: 2026-05-18 15:01:59.472322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '35fbd8e86e99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox'))
    )
    op.create_table('parse_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('storage_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'processed', 'failed', name='parse_request_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anon_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parse_requests'))
    )
    op.create_table('request_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('parse_request_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parse_request_id'], ['parse_requests.id'], name=op.f('fk_request_files_parse_request_id_parse_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_files'))
    )
    op.create_table('parse_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'processed', 'failed', name='parse_job_status'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('request_file_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['request_file_id'], ['request_files.id'], name=op.f('fk_parse_jobs_request_file_id_request_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['parse_requests.id'], name=op.f('fk_parse_jobs_request_id_parse_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parse_jobs')),
    sa.UniqueConstraint('request_file_id', name=op.f('uq_parse_jobs_request_file_id'))
    )
    op.create_table('parser_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('parse_job_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parse_job_id'], ['parse_jobs.id'], name=op.f('fk_parser_outputs_parse_job_id_parse_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parser_outputs')),
    sa.UniqueConstraint('parse_job_id', name=op.f('uq_parser_outputs_parse_job_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parser_outputs')
    op.drop_table('parse_jobs')
    op.drop_table('request_files')
    op.drop_table('parse_requests')
    op.drop_table('outbox')
    # ### end Alembic commands ###
