"""added storage id

Revision ID: 93aee74ecdae
Revises: 0e3a74eaf7a5
Create Date: 2026-05-16 18:05:59.015879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '93aee74ecdae'
down_revision: Union[str, Sequence[str], None] = '0e3a74eaf7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
