"""added parser request

Revision ID: e8ed57530d0e
Revises: fc797e2a9990
Create Date: 2026-05-16 17:46:45.904661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'e8ed57530d0e'
down_revision: Union[str, Sequence[str], None] = 'fc797e2a9990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parse_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'processed', 'failed', name='parse_request_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parse_requests'))
    )
    op.create_table('parser_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('parse_request_id', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parse_request_id'], ['parse_requests.id'], name=op.f('fk_parser_files_parse_request_id_parse_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parser_files'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parser_files')
    op.drop_table('parse_requests')
    # ### end Alembic commands ###
